spring.application.name=${APP_NAME:new-features-react-19_v1}
server.port=${SERVER_PORT:9001}

logging.level.org.springframework.kafka.transaction=TRACE
logging.level.org.springframework.transaction=TRACE
logging.level.org.apache.kafka.clients.producer.internals.TransactionManager=TRACE
logging.level.org.springframework.kafka.transaction.KafkaTransactionManager=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=TRACE
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
# Logs handler mapping like @GetMapping, @PostMapping
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
# Logs request details (good with CommonsRequestLoggingFilter)
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=TRACE
# Logs controller-level entry (best if you're using @RestController/@Controller)
logging.level.org.springframework.web.method.support.InvocableHandlerMethod=TRACE

