#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: spring-tomcat-max-connections-docker-2
#spec:
#  template:
#    metadata:
#      name: spring-tomcat-max-connections-docker-2-pod
#    spec:
#      containers:
#      - name: spring-tomcat-max-connections-docker-2
#        image: spring-tomcat-max-connections-docker-2-app
#      restartPolicy: OnFailure
      
# First, add the API
apiVersion: apps/v1
# This will be the deployment setup
kind: Deployment
metadata:
  # Name your Deployment here
  name: spring-tomcat-max-connections-docker-2
  labels:
    # label your deployment
    app: spring-tomcat-max-connections-docker-2
spec:
  # The number of pods/replicas to run
  replicas: 1            
  selector:
    matchLabels:
    # selector to match the pod
      app: spring-tomcat-max-connections-docker-2
  template:
    metadata:
      labels:
      # label your pod
        app: spring-tomcat-max-connections-docker-2
    spec:
      containers:
      # Add the container name for Kubernetes
      - name: spring-tomcat-max-connections-docker-2
      # Add the local image name
        image: spring-tomcat-max-connections-docker-2
        # never pull the image policy
        imagePullPolicy: Never
        ports:
        # port for running the container
        - containerPort: 3000

---
# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: spring-tomcat-max-connections-docker-2
spec:
  selector:
    # selector that matches the pod
    app: spring-tomcat-max-connections-docker-2
  # type of service
  type: LoadBalancer
  ports:
  - protocol: TCP
    # port for exposing the service
    port: 5000
    # portfor exposing the pod
    targetPort: 9001
    # port for exposing the node
    nodePort: 31110