server:
  port: 9001

spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/junittests?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    generate-ddl: true