// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Redis_Dao_Architecture_V2;

/************************************************************/
/**
 * 
 */
public class loginUserInterationDiagram {
}
