spring.application.name=${APPLICATION_NAME:websocket-application-2}
server.port=${SERVER_PORT:8080}

logging.level.web=${LOGGING_LEVEL:TRACE}
logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.messaging=TRACE
